#!/bin/sh

set -eu

version='2.0.1'
me="${0##*/}"
tasks_dir="${0%/*}/../share/ayusin/tasks.d"
user_dir="${HOME}/.ayusin"
user_tasks_dir="${user_dir}/tasks.d"
common_file="${0%/*}/../share/ayusin/common"
rc=0

# shellcheck disable=SC2120
usage() {
	# shellcheck disable=SC3043
	local rc
	rc=${1:-0}
	echo "Usage: $me [options]"
	echo
	echo '       --version           Show version'
	echo '       -v, --verbose       Show commands as they are executed'
	echo '       -n, --dry-run       Show commands that would have been executed'
	echo '       -c, --common        Show path to common file'
	echo '       --tasks-dir         Show path to tasks directory'
	echo '       --user-dir          Show path to user directory'
	echo '       --user-tasks-dir    Show path to user tasks directory'
	echo '       -h, --help          Show this help'
	exit "$rc"
}

while [ $# -ne 0 ]; do
	case $1 in
		--version)
			echo "$version"
			exit
			;;
		-v|--verbose)
			opt_verbose=1
			shift
			;;
		-n|--dry-run)
			opt_dryrun=1
			shift
			;;
		-c|--common)
			echo "$common_file"
			exit
			;;
		--tasks-dir)
			echo "$tasks_dir"
			exit
			;;
		--user-dir)
			echo "$user_dir"
			exit
			;;
		--user-tasks-dir)
			echo "$user_tasks_dir"
			exit
			;;
		-h|--help)
			# shellcheck disable=SC2119
			usage
			;;
		*)
			echo "Error: Unknown option: $1" 1>&2
			exit 1
			;;
	esac
done

AYUSIN=1
AYUSIN_VERBOSE="${opt_verbose:-}"
AYUSIN_DRYRUN="${opt_dryrun:-}"
AYUSIN_USER_DIR="$user_dir"
AYUSIN_ME="$me"
export AYUSIN AYUSIN_VERBOSE AYUSIN_DRYRUN AYUSIN_USER_DIR AYUSIN_ME

run-parts --exit-on-error "$tasks_dir" || rc=$((rc + 1))
if [ -d "$user_tasks_dir" ]; then
	run-parts --exit-on-error "$user_tasks_dir" || rc=$((rc + 1))
fi

exit "$rc"
