#!/bin/sh

set -eu

tasks_dir=$(ayusin --tasks-dir)
user_dir=$(ayusin --user-dir)
user_tasks_dir=$(ayusin --user-tasks-dir)

AYUSIN=1
AYUSIN_USER_DIR="$user_dir"
AYUSIN_ME="${0##*/}"
export AYUSIN AYUSIN_USER_DIR AYUSIN_ME

inhibit_sleep_exec() {
	test -n "${1:-}"           || exit 1
	command -v "$1" >/dev/null || exit 1

	if command -v caffeinate >/dev/null; then
		exec caffeinate -i "$@"
	else
		exec "$@"
	fi
}

if [ -z "${1:-}" ]; then
	echo '❗️ Please specify the task to run' 1>&2
	exit 1
fi

cmd=$(PATH=".:${user_tasks_dir}:${tasks_dir}"; command -v "$1" || true)
shift

if [ -n "$cmd" ]; then
	echo "🎬 Running: $cmd"
	inhibit_sleep_exec "$cmd" "$@"
fi

echo '❗️ Task not found' 1>&2
exit 1
