#!/bin/sh

# shellcheck source=../common
. "${0%/*}/../common"
task_description='Powerlevel10k upgrade'

task_start

test -d "${HOME}/.oh-my-zsh/custom/themes/powerlevel10k" || task_skip
# shellcheck disable=SC2119
$DRYRUN git -C "${HOME}/.oh-my-zsh/custom/themes/powerlevel10k" \
            pull --autostash --rebase --stat || task_fail

task_end
